chat:
  client:
    claude:
      enabled: true
    ollama:
      enabled: true
    ollama-docker:
      enabled: true

spring:
  application:
    name: spring-ai-claude-section01
  ai:
    anthropic:
      api-key: ${PERSONAL_CLAUDE_API_KEY}
      chat:
        options:
          model: claude-haiku-4-5
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:1b
      init:
        pull-model-strategy: when_missing

ollama:
  secondary:
    base-url: http://localhost:11435  # Ollama Docker Port
    model: llama3.2:1b

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
